### ISSUE TITLE
change service in main.js

### ISSUE THREAD

**Issue by enlowe** [CoastalResilienceNetwork/water_share#1]
update service (already created) to:
Dev:
http://dev.services.coastalresilience.org:6080/arcgis/rest/services/Water_Blueprint/Water_Scarcity/MapServer

Production:
http://services.coastalresilience.org:6080/arcgis/rest/services/Water_Blueprint/Water_Scarcity/MapServer

...following DM protocol

**Comment by cschneebeck** [comment]
Done
